# Preprocesado y análisis de estacionariedad

Este notebook analiza la estacionariedad de las series utilizadas en el trabajo. Para cada ETF se estudian distintas variables, como el precio ajustado, el logaritmo del precio, el retorno simple, el retorno logarítmico, el volumen y el volumen en dólares.

El objetivo es comprobar qué representación de los datos es más adecuada para aplicar modelos de series temporales. A partir de los resultados de los tests ADF y KPSS, se identifican los ETFs cuyos retornos no presentan un comportamiento estacionario y se genera la lista final de activos válidos para los siguientes experimentos.

In [1]:
import pandas as pd

# Cargar precios ajustados
adj_close = pd.read_csv(
    "../Datos_csv/adj_close.csv",
    index_col=0,
    parse_dates=True
)

# Cargar volumen
volume = pd.read_csv(
    "../Datos_csv/volume.csv",
    index_col=0,
    parse_dates=True
)

La metodología se ilustra con un activo representativo. Seleccionamos la varibel principal (retornos en formato logarítmico)

In [2]:
import numpy as np
# Retornos
ret_simple = adj_close.pct_change()
ret_log = np.log(adj_close)
ret_log_diff = np.log(adj_close).diff() #diferencia con el dia anterior
dollar_vol = adj_close * volume

In [ ]:
#  Lista de ETFs 

tickers = list(adj_close.columns)
print("Número de ETFs:", len(tickers))
print(" Listado:", tickers)

Número de ETFs: 63
 Listado: ['AGG', 'BIL', 'BND', 'DBC', 'DIA', 'DVY', 'EEM', 'EFA', 'EWG', 'EWJ', 'EWQ', 'EWT', 'EWU', 'EWY', 'EWZ', 'FXI', 'GLD', 'HYG', 'IAU', 'IEF', 'IEFA', 'IEMG', 'IJR', 'INDA', 'ITOT', 'IVV', 'IWD', 'IWF', 'IWM', 'JNK', 'LQD', 'MCHI', 'MDY', 'MTUM', 'QQQ', 'QUAL', 'SCHD', 'SHY', 'SLV', 'SPY', 'TIP', 'TLT', 'USMV', 'USO', 'VEA', 'VIG', 'VLUE', 'VNQ', 'VOO', 'VTI', 'VTV', 'VUG', 'VWO', 'XLB', 'XLE', 'XLF', 'XLI', 'XLK', 'XLP', 'XLRE', 'XLU', 'XLV', 'XLY']

Se analiza la estacionariedad de distintas transformaciones de la serie con el objetivo de identificar la representación más adecuada para la modelización temporal.

In [ ]:
import numpy as np
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tools.sm_exceptions import InterpolationWarning 
import warnings
warnings.filterwarnings("ignore", category=InterpolationWarning)

def tests_estacionariedad(serie):
    x = np.asarray(serie, float)
    x = x[~np.isnan(x)]
    #  ADF (H0: no estacionaria) 
    adf_stat, adf_p, adf_lags, adf_n, adf_crit, adf_icbest = adfuller(x, autolag='AIC')
    

    kpss_stat, kpss_p, kpss_lags, kpss_crit = kpss(x, regression='c', nlags='auto' )
    if kpss_p <= 0.01 and adf_p>0.01: # rechazamos KPSS, pero no ADF
        s = "no estacionario"
    elif kpss_p > 0.01 and adf_p<=0.01: # rechazamos ADF, pero no KPSS 
        s = "estacionario"
    elif kpss_p > 0.01 and adf_p > 0.01: # no se rechaza nada        
        s = "no concluyente"
    else:
        s = "resultados inconsistentes" 
    return s

In [ ]:
# Estacionariedad (una fila por ETF y por serie)
estacionariedad_rows = []

for etf in tickers:

    #  Extraer series del ETF
  
    serie_adj_close     = adj_close[etf].dropna()
    serie_ret_simple    = ret_simple[etf].dropna()
    serie_log_precio    = ret_log[etf].dropna()
    serie_ret_log_diff  = ret_log_diff[etf].dropna()
    serie_dollar_vol    = dollar_vol[etf].dropna()
    serie_volume        = volume[etf].dropna()

    #  Estacionariedad

    series_a_testear = {
        "Adj_close": serie_adj_close,
        "log(Adj_close)": serie_log_precio,
        "retorno_simple": serie_ret_simple,
        "retorno_logaritmico": serie_ret_log_diff,
        "dollar_volume": serie_dollar_vol,
        "volume": serie_volume
    }

    res_est = []
    for nombre, s in series_a_testear.items():
        if len(s) < 50:
            estado = "insuficientes_datos"
        else:
            estado = tests_estacionariedad(s)

        row = {
            "ETF": etf,
            "Serie": nombre,
            "N_obs": len(s),
            "Inicio": s.index.min().date(),
            "Fin": s.index.max().date(),
            "Conclusión": estado
        }
        estacionariedad_rows.append(row)
        res_est.append(row)

    display(pd.DataFrame(res_est).head())

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,AGG,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,AGG,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,AGG,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,AGG,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,AGG,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  BIL            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  BIL       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  BIL       retorno_simple   1275  2021-01-05  2026-02-02  no estacionario
3  BIL  retorno_logaritmico   1275  2021-01-05  2026-02-02  no estacionario
4  BIL        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,BND,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,BND,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,BND,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,BND,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,BND,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  DBC            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  DBC       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  DBC       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  DBC  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  DBC        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,DIA,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,DIA,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,DIA,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,DIA,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,DIA,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  DVY            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  DVY       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  DVY       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  DVY  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  DVY        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,EEM,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,EEM,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,EEM,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,EEM,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,EEM,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  EFA            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  EFA       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  EFA       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  EFA  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  EFA        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,EWG,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,EWG,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,EWG,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,EWG,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,EWG,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  EWJ            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  EWJ       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  EWJ       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  EWJ  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  EWJ        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,EWQ,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,EWQ,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,EWQ,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,EWQ,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,EWQ,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,EWT,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,EWT,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,EWT,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,EWT,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,EWT,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,EWU,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,EWU,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,EWU,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,EWU,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,EWU,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,EWY,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,EWY,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,EWY,retorno_simple,1275,2021-01-05,2026-02-02,resultados inconsistentes
3,EWY,retorno_logaritmico,1275,2021-01-05,2026-02-02,resultados inconsistentes
4,EWY,dollar_volume,1276,2021-01-04,2026-02-02,no estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  EWZ            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  EWZ       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  EWZ       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  EWZ  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  EWZ        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,FXI,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,FXI,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,FXI,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,FXI,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,FXI,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,GLD,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,GLD,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,GLD,retorno_simple,1275,2021-01-05,2026-02-02,resultados inconsistentes
3,GLD,retorno_logaritmico,1275,2021-01-05,2026-02-02,resultados inconsistentes
4,GLD,dollar_volume,1276,2021-01-04,2026-02-02,no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,HYG,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,HYG,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,HYG,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,HYG,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,HYG,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,IAU,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,IAU,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,IAU,retorno_simple,1275,2021-01-05,2026-02-02,resultados inconsistentes
3,IAU,retorno_logaritmico,1275,2021-01-05,2026-02-02,resultados inconsistentes
4,IAU,dollar_volume,1276,2021-01-04,2026-02-02,no estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  IEF            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  IEF       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  IEF       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  IEF  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  IEF        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,IEFA,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,IEFA,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,IEFA,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,IEFA,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,IEFA,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

    ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  IEMG            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  IEMG       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  IEMG       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  IEMG  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  IEMG        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,IJR,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,IJR,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,IJR,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,IJR,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,IJR,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

    ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  INDA            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  INDA       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  INDA       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  INDA  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  INDA        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

    ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  ITOT            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  ITOT       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  ITOT       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  ITOT  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  ITOT        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,IVV,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,IVV,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,IVV,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,IVV,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,IVV,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  IWD            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  IWD       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  IWD       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  IWD  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  IWD        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  IWF            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  IWF       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  IWF       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  IWF  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  IWF        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,IWM,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,IWM,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,IWM,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,IWM,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,IWM,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  JNK            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  JNK       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  JNK       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  JNK  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  JNK        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  LQD            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  LQD       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  LQD       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  LQD  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  LQD        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,MCHI,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,MCHI,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,MCHI,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,MCHI,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,MCHI,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  MDY            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  MDY       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  MDY       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  MDY  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  MDY        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,MTUM,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,MTUM,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,MTUM,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,MTUM,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,MTUM,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  QQQ            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  QQQ       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  QQQ       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  QQQ  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  QQQ        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,QUAL,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,QUAL,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,QUAL,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,QUAL,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,QUAL,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

    ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  SCHD            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  SCHD       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  SCHD       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  SCHD  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  SCHD        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,SHY,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,SHY,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,SHY,retorno_simple,1275,2021-01-05,2026-02-02,resultados inconsistentes
3,SHY,retorno_logaritmico,1275,2021-01-05,2026-02-02,resultados inconsistentes
4,SHY,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  SLV            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  SLV       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  SLV       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  SLV  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  SLV        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,SPY,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,SPY,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,SPY,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,SPY,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,SPY,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,TIP,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,TIP,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,TIP,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,TIP,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,TIP,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  TLT            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  TLT       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  TLT       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  TLT  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  TLT        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

    ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  USMV            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  USMV       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  USMV       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  USMV  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  USMV        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  USO            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  USO       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  USO       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  USO  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  USO        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  VEA            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  VEA       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  VEA       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  VEA  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  VEA        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  VIG            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  VIG       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  VIG       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  VIG  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  VIG        dollar_volume   1276  2021-01-04  2026-02-02   no concluyente

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,VLUE,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,VLUE,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,VLUE,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,VLUE,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,VLUE,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,VNQ,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,VNQ,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,VNQ,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,VNQ,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,VNQ,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,VOO,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,VOO,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,VOO,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,VOO,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,VOO,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  VTI            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  VTI       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  VTI       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  VTI  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  VTI        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  VTV            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  VTV       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  VTV       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  VTV  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  VTV        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  VUG            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  VUG       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  VUG       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  VUG  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  VUG        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  VWO            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  VWO       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  VWO       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  VWO  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  VWO        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  XLB            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  XLB       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  XLB       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  XLB  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  XLB        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  XLE            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  XLE       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  XLE       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  XLE  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  XLE        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  XLF            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  XLF       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  XLF       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  XLF  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  XLF        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,XLI,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,XLI,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,XLI,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,XLI,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,XLI,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  XLK            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  XLK       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  XLK       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  XLK  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  XLK        dollar_volume   1276  2021-01-04  2026-02-02  no estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,XLP,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,XLP,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,XLP,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,XLP,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,XLP,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

    ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  XLRE            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  XLRE       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  XLRE       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  XLRE  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  XLRE        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  XLU            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  XLU       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  XLU       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  XLU  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  XLU        dollar_volume   1276  2021-01-04  2026-02-02     estacionario

,ETF,Serie,N_obs,Inicio,Fin,Conclusión
0,XLV,Adj_close,1276,2021-01-04,2026-02-02,no estacionario
1,XLV,log(Adj_close),1276,2021-01-04,2026-02-02,no estacionario
2,XLV,retorno_simple,1275,2021-01-05,2026-02-02,estacionario
3,XLV,retorno_logaritmico,1275,2021-01-05,2026-02-02,estacionario
4,XLV,dollar_volume,1276,2021-01-04,2026-02-02,resultados inconsistentes

   ETF                Serie  N_obs      Inicio         Fin       Conclusión
0  XLY            Adj_close   1276  2021-01-04  2026-02-02  no estacionario
1  XLY       log(Adj_close)   1276  2021-01-04  2026-02-02  no estacionario
2  XLY       retorno_simple   1275  2021-01-05  2026-02-02     estacionario
3  XLY  retorno_logaritmico   1275  2021-01-05  2026-02-02     estacionario
4  XLY        dollar_volume   1276  2021-01-04  2026-02-02   no concluyente

ELIMINAMOS LOS ETFS NO ESTACIONARIOS EN RETORNOS

In [ ]:

# Convertimos la lista acumulada en DataFrame
estacionariedad_df = pd.DataFrame(estacionariedad_rows)

# ETFs válidos
etfs_validos = []

# ETFs eliminados
etfs_eliminados = []

for etf in tickers:
    
    # Filtramos solo las filas de ese ETF
    df_etf = estacionariedad_df[estacionariedad_df["ETF"] == etf]
    
    ret_simple_estado = df_etf[df_etf["Serie"] == "retorno_simple"]["Conclusión"].values
    ret_log_estado    = df_etf[df_etf["Serie"] == "retorno_logaritmico"]["Conclusión"].values
    
    if (
        len(ret_simple_estado) > 0 and
        len(ret_log_estado) > 0 and
        ret_simple_estado[0] == "estacionario" or
        ret_log_estado[0] == "estacionario"
    ):
        etfs_validos.append(etf)
    else:
        etfs_eliminados.append(etf)

print("Número total ETFs originales:", len(tickers))
print("Número ETFs válidos:", len(etfs_validos))
print("Número ETFs eliminados:", len(etfs_eliminados))

print("\nETFs eliminados:")
display(pd.DataFrame(etfs_eliminados, columns=["ETF eliminado"]))

tickers_filtrados = etfs_validos

Número total ETFs originales: 63
Número ETFs válidos: 58
Número ETFs eliminados: 5

ETFs eliminados:

  ETF eliminado
0           BIL
1           EWY
2           GLD
3           IAU
4           SHY

In [7]:
import json
import os

resultado = {
    "tickers_filtrados": tickers_filtrados,
    "etfs_eliminados": etfs_eliminados
}

out_path = "../Datos_csv/tickers_estacionalidad.json"
with open(out_path, 'w', encoding='utf-8') as fout:
    json.dump(resultado, fout, indent=2, ensure_ascii=False)

print(f"Guardado en: {out_path}")
print(f"ETFs validos  : {len(tickers_filtrados)}")
print(f"ETFs eliminados: {etfs_eliminados}")

Guardado en: ../Datos_csv/tickers_estacionalidad.json
ETFs validos  : 58
ETFs eliminados: ['BIL', 'EWY', 'GLD', 'IAU', 'SHY']