# Preparación del dataset semanal

Construye el dataset semanal agrupando retornos logarítmicos diarios. Las features incluyen el retorno de cada ETF, la variación de volumen y variables de calendario. Se generan cinco versiones: sin lags y con 1, 2, 3 y 4 semanas de histórico adicional.

In [ ]:
import pandas as pd
import numpy as np

# Datos del preprocesado
adj_close = pd.read_csv(
    "../Datos_csv/adj_close.csv",
    index_col=0,
    parse_dates=True
)

volume = pd.read_csv(
    "../Datos_csv/volume.csv",
    index_col=0,
    parse_dates=True
)

In [310]:
to_drop = ['BIL', 'EWY', 'GLD', 'IAU', 'SHY']

adj_close = adj_close.drop(columns=to_drop)
volume    = volume.drop(columns=to_drop)

In [311]:
# Retornos logarítmicos diarios
ret_log_diff = np.log(adj_close).diff()

In [312]:
ret_log_diff=ret_log_diff[1:]

In [313]:
# también recortamos volumen para que empiece en las mismas fechas
volume = volume.loc[ret_log_diff.index].copy()

In [314]:

fechas = ret_log_diff.index.to_series()
iso_cal = ret_log_diff.index.isocalendar()
week_info = pd.DataFrame(index=ret_log_diff.index)

# Año ISO y número de semana ISO
week_info["year"] = iso_cal.year.astype(int)
week_info["semana"] = iso_cal.week.astype(int)

# Mes natural de cada fecha
week_info["mes"] = fechas.dt.month.values

# Claves de mes y trimestre para detectar cambios reales en días de trading
periodo_mes = fechas.dt.to_period("M")
periodo_trimestre = fechas.dt.to_period("Q")

# INICIO DE MES REAL:
# 1 si esa fecha es el primer día de trading de su mes, Esto compara cada fecha con la anterior:
#si el mes cambia respecto al registro anterior, entonces esa fecha es el primer día de trading del nuevo mes
week_info["inicio_mes"] = (periodo_mes != periodo_mes.shift(1)).astype(int).values

# FIN DE MES REAL:
# 1 si esa fecha es el último día de trading de su mes
week_info["fin_mes"] = (periodo_mes != periodo_mes.shift(-1)).astype(int).values

# FIN DE TRIMESTRE REAL:
# 1 si esa fecha es el último día de trading de su trimestre
week_info["fin_trimestre"] = (periodo_trimestre != periodo_trimestre.shift(-1)).astype(int).values
#inicio trimestre
week_info["inicio_trimestre"] = (periodo_trimestre != periodo_trimestre.shift(1)).astype(int).values

# Clave semana-año para no mezclar semanas de años distintos
week_info["week_key"] = (
    week_info["year"].astype(str)
    + "-W"
    + week_info["semana"].astype(str).str.zfill(2)
)

Se usa el primer y último día de trading real del mes/trimestre, no el día natural, para evitar que caiga en fin de semana o festivo.

In [315]:
# Retorno semanal por ETF = suma de retornos log diarios
ret_weekly = ret_log_diff.groupby(week_info["week_key"]).mean() 
ret_weekly = ret_weekly.add_prefix("ret_semanal_") 

# Volumen semanal por ETF = suma semanal
vol_weekly = volume.groupby(week_info["week_key"]).mean()
vol_weekly = vol_weekly.add_prefix("volumen_semanal_")

# Variables temporales semanales
year_weekly = week_info.groupby("week_key")["year"].first()
semana_weekly = week_info.groupby("week_key")["semana"].first()
mes_weekly = week_info.groupby("week_key")["mes"].last()

# Si la semana contiene al menos un día que sea:
# - primer día de trading del mes
# - último día de trading del mes
# - último día de trading del trimestre
inicio_mes_weekly = week_info.groupby("week_key")["inicio_mes"].max()
fin_mes_weekly = week_info.groupby("week_key")["fin_mes"].max()
inicio_trimestre_weekly = week_info.groupby("week_key")["inicio_trimestre"].max()
fin_trimestre_weekly = week_info.groupby("week_key")["fin_trimestre"].max()

# DataFrame base semanal
df_semanal = pd.DataFrame(index=ret_weekly.index)
df_semanal["year"] = year_weekly
df_semanal["semana"] = semana_weekly
df_semanal["mes"] = mes_weekly
df_semanal["inicio_mes"] = inicio_mes_weekly
df_semanal["fin_mes"] = fin_mes_weekly
df_semanal["inicio_trimestre"] = inicio_trimestre_weekly
df_semanal["fin_trimestre"] = fin_trimestre_weekly

# Unir todo
df_semanal = pd.concat(
    # [df_semanal, ret_weekly, vol_weekly, n_dias_weekly],
    [df_semanal, ret_weekly, vol_weekly],
    axis=1
).reset_index().rename(columns={"index": "week_key"})

Diferencias logarítmicas del volumen:

Mide la variación relativa del volumen entre semanas, para detectar aumentos o caídas en la actividad del mercado.

Ratio de volumen: compara el volumen actual con la media de las últimas 4 semanas para detectar actividad anormal.

In [316]:
etfs = adj_close.columns.tolist()

vol_features = {}

for etf in etfs:
    col_vol = f"volumen_semanal_{etf}"

    # cambio logarítmico del volumen
    vol_features[f"volumen_log_diff_{etf}"] = (
        np.log(df_semanal[col_vol].replace(0, np.nan)).diff()
    )

# pasar todo a DataFrame de una vez
vol_features_df = pd.DataFrame(vol_features, index=df_semanal.index)

# unir de una vez y desfragmentar
df_semanal = pd.concat([df_semanal, vol_features_df], axis=1).copy()

# eliminar volumen absoluto
cols_vol = [f"volumen_semanal_{etf}" for etf in etfs]
df_semanal = df_semanal.drop(columns=cols_vol).copy()

In [317]:

# 9. TARGETS: RETORNO DE LA SEMANA SIGUIENTE DE CADA ETF
targets_dict = {}

for etf in etfs:
    col_ret = f"ret_semanal_{etf}"
    targets_dict[f"target_{etf}"] = df_semanal[col_ret].shift(-1)

targets_df = pd.DataFrame(targets_dict, index=df_semanal.index)

df_semanal = pd.concat([df_semanal, targets_df], axis=1).copy()

In [318]:
import pandas as pd

pd.set_option("display.max_columns", None) 
df_semanal.head()

,week_key,year,semana,mes,inicio_mes,fin_mes,inicio_trimestre,fin_trimestre,ret_semanal_AGG,ret_semanal_BND,ret_semanal_DBC,ret_semanal_DIA,ret_semanal_DVY,ret_semanal_EEM,ret_semanal_EFA,ret_semanal_EWG,ret_semanal_EWJ,ret_semanal_EWQ,ret_semanal_EWT,ret_semanal_EWU,ret_semanal_EWZ,ret_semanal_FXI,ret_semanal_HYG,ret_semanal_IEF,ret_semanal_IEFA,ret_semanal_IEMG,ret_semanal_IJR,ret_semanal_INDA,ret_semanal_ITOT,ret_semanal_IVV,ret_semanal_IWD,ret_semanal_IWF,ret_semanal_IWM,ret_semanal_JNK,ret_semanal_LQD,ret_semanal_MCHI,ret_semanal_MDY,ret_semanal_MTUM,ret_semanal_QQQ,ret_semanal_QUAL,ret_semanal_SCHD,ret_semanal_SLV,ret_semanal_SPY,ret_semanal_TIP,ret_semanal_TLT,ret_semanal_USMV,ret_semanal_USO,ret_semanal_VEA,ret_semanal_VIG,ret_semanal_VLUE,ret_semanal_VNQ,ret_semanal_VOO,ret_semanal_VTI,ret_semanal_VTV,ret_semanal_VUG,ret_semanal_VWO,ret_semanal_XLB,ret_semanal_XLE,ret_semanal_XLF,ret_semanal_XLI,ret_semanal_XLK,ret_semanal_XLP,ret_semanal_XLRE,ret_semanal_XLU,ret_semanal_XLV,ret_semanal_XLY,volumen_log_diff_AGG,volumen_log_diff_BND,volumen_log_diff_DBC,volumen_log_diff_DIA,volumen_log_diff_DVY,volumen_log_diff_EEM,volumen_log_diff_EFA,volumen_log_diff_EWG,volumen_log_diff_EWJ,volumen_log_diff_EWQ,volumen_log_diff_EWT,volumen_log_diff_EWU,volumen_log_diff_EWZ,volumen_log_diff_FXI,volumen_log_diff_HYG,volumen_log_diff_IEF,volumen_log_diff_IEFA,volumen_log_diff_IEMG,volumen_log_diff_IJR,volumen_log_diff_INDA,volumen_log_diff_ITOT,volumen_log_diff_IVV,volumen_log_diff_IWD,volumen_log_diff_IWF,volumen_log_diff_IWM,volumen_log_diff_JNK,volumen_log_diff_LQD,volumen_log_diff_MCHI,volumen_log_diff_MDY,volumen_log_diff_MTUM,volumen_log_diff_QQQ,volumen_log_diff_QUAL,volumen_log_diff_SCHD,volumen_log_diff_SLV,volumen_log_diff_SPY,volumen_log_diff_TIP,volumen_log_diff_TLT,volumen_log_diff_USMV,volumen_log_diff_USO,volumen_log_diff_VEA,volumen_log_diff_VIG,volumen_log_diff_VLUE,volumen_log_diff_VNQ,volumen_log_diff_VOO,volumen_log_diff_VTI,volumen_log_diff_VTV,volumen_log_diff_VUG,volumen_log_diff_VWO,volumen_log_diff_XLB,volumen_log_diff_XLE,volumen_log_diff_XLF,volumen_log_diff_XLI,volumen_log_diff_XLK,volumen_log_diff_XLP,volumen_log_diff_XLRE,volumen_log_diff_XLU,volumen_log_diff_XLV,volumen_log_diff_XLY,target_AGG,target_BND,target_DBC,target_DIA,target_DVY,target_EEM,target_EFA,target_EWG,target_EWJ,target_EWQ,target_EWT,target_EWU,target_EWZ,target_FXI,target_HYG,target_IEF,target_IEFA,target_IEMG,target_IJR,target_INDA,target_ITOT,target_IVV,target_IWD,target_IWF,target_IWM,target_JNK,target_LQD,target_MCHI,target_MDY,target_MTUM,target_QQQ,target_QUAL,target_SCHD,target_SLV,target_SPY,target_TIP,target_TLT,target_USMV,target_USO,target_VEA,target_VIG,target_VLUE,target_VNQ,target_VOO,target_VTI,target_VTV,target_VUG,target_VWO,target_XLB,target_XLE,target_XLF,target_XLI,target_XLK,target_XLP,target_XLRE,target_XLU,target_XLV,target_XLY
0,2021-W01,2021,1,1,1,0,1,0,-0.002042,-0.002281,0.010383,0.007109,0.012052,0.012701,0.008017,0.005839,0.009299,0.006168,0.011315,0.012966,0.007608,0.010676,0.000716,-0.003652,0.008001,0.011714,0.017702,0.008355,0.009113,0.008249,0.010667,0.006692,0.017728,0.000804,-0.003056,0.012631,0.015672,0.012029,0.007735,0.006175,0.009732,-0.018838,0.008313,-0.001964,-0.010071,0.005358,0.022504,0.008591,0.006345,0.011569,0.002723,0.008261,0.009436,0.009851,0.007234,0.010313,0.016233,0.021808,0.015338,0.009091,0.005529,0.000674,0.001971,0.004901,0.009639,0.014278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575
1,2021-W02,2021,2,1,0,0,0,0,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575,-0.117361,-0.086574,-0.539732,-0.459750,-0.292106,-0.256894,-0.017097,-0.504441,-0.288985,0.146919,-0.384660,-0.024032,-0.021922,-0.680665,0.200763,-0.129573,0.133340,0.202425,0.300938,0.028507,-0.114187,0.205928,0.176201,0.052224,-0.149952,-0.075401,0.009488,-0.179850,-0.440872,0.933530,-0.243510,0.630144,-0.176504,-0.481412,-0.251597,-0.198469,-0.256328,0.642472,-0.516593,-0.123466,-0.090498,0.430339,0.262899,-0.227624,-0.393088,0.233110,0.333712,-0.265088,-0.673632,-0.004085,-0.095183,-0.250324,-0.153681,-0.279392,-0.182059,-0.069886,-0.536523,-0.028911,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401
2,2021-W03,2021,3,1,0,0,0,0,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401,-0.108402,0.070663,0.225736,-0.215147,-0.009009,-0.037758,-0.170444,-0.251776,-0.130704,-1.392636,-0.052462,-0.323851,-0.110371,0.360270,-0.459197,-0.460806,-0.246064,-0.276663,-0.336541,-0.036602,-0.288774,-0.221239,-0.474917,0.014214,-0.230680,-0.249003,0.076559,0.133429,-0.073125,-0.825676,-0.118380,0.441607,0.017676,-0.405491,-0.135656,-0.103573,-0.378927,-0.545948,-0.283308,-0.213511,-0.118714,-0.916898,-0.275064,-0.138688,0.015674,-0.520023,-0.511758,-0.227270,-0.227945,-0.307283,0.009988,-0.185710,-0.344825,-0.190748,-0.199547,-0.007754,-0.225129,-0.215411,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746
3,2021-W04,2021,4,1,0,1,0,0,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746,-0.078063,-0.279824,-0.074341,0.775598,0.455206,0.059252,0.385649,0.546404,0.362695,0.400013,0.025057,0.270618,0.039978,0.044538,0.507807,0.296918,0.266312,-0.052148,0.312374,0.301928,0.550374,0.004164,0.438061,-0.088176,0.437582,0.808351,-0.091883,0.082252,0.123152,-0.083392,0.536044,0.441543,0.312325,1.083251,0.537474,-0.025717,0.202761,0.101343,0.133127,0.424749,0.190661,-0.141083,0.237280,0.409132,0.435398,0.036222,-0.005418,0.259145,0.523120,0.275833,0.171819,0.683245,0.463449,0.633732,0.787498,0.216596,0.497789,0.478444,-0.000698,-0.000760,0.008759,0.007676,0.009628,0.010701,0.006309,0.007364,0.006636,0.008167,0.009320,0.003931,0.011591,0.009225,0.001993,-0.001239,0.006879,0.010855,0.010696,0.015102,0.010069,0.009257,0.009361,0.009955,0.015072,0.002327,-0.000804,0.010852,0.011566,0.012135,0.010406,0.008818,0.007625,-0.000320,0.009313,-0.000438,-0.005062,0.005054,0.016419,0.007126,0.006828,0.008568,0.007281,0.009338,0.010170,0.007908,0.011039,0.010626,0.008019,0.015836,0.012972,0.009716,0.009675,0.005145,0.006319,0.004581,0.001110,0.012235
4,2021-W05,2021,5,2,1,0,0,0,-0.000698,-0.000760,0.008759,0.007676,0.009628,0.010701,0.006309,0.007364,0.006636,0.008167,0.009320,0.003931,0.011591,0.009225,0.001993,-0.001239,0.006879,0.010855,0.010696,0.015102,0.010069,0.009257,0.009361,0.009955,0.015072,0.002327,-0.000804,0.010852,0.011566,0.012135,0.010406,0.008818,0.007625,-0.000320,0.009313,-0.000438,-0.005062,0.005054,0.016419,0.007126,0.006828,0.008568,0.007281,0.009338,0.010170,0.007908,0.011039,0.010626,0.008019,0.015836,0.012972,0.009716,0.009675,0.005145,0.006319,0.004581,0.001110,0.012235,-0.051107,-0.032336,0.656292,-0.655463,-0.928930,-0.211436,-0.576054,-0.382393,-0.182862,-0.762121,-0.096317,-0.487200,-0.192697,-0.257301,-0.353126,-0.438679,-0.352534,-0.204874,-0.494990,-0.287499,-0.118312,-0.346173,-0.160283,0.001141,-0.371301,-0.522335,-0.240154,-0.300759,-0.472664,0.170104,-0.446259,-1.255911,-0.268505,0.476288,-0.460796,0.328236,-0.092998,-0.334069,0.306580,-0.472144,-0.140701,-0.021730,-0.382191,-0.385021,-0.621943,-0.201325,-0.211008,-0.342546,-0.301719,-0.187869,-0.358571,-0.678380,-0.569198,-0.473119,-0.829476,-0.448354,-0.036454,-0.653051,-0.000223,-0.000276,0.005592,0.002234,0.003458,0.005472,0.004238,0.001891,0.006535,0.002591,0.004704,0.004906,-0.001107,0.007182,0.000593,-0.000068,0.004100,0.005503,0.007063,0.003755,0.003203,0.002584,0.003824,0.002561,0.004999,0.000694,-0.000163,0.008434,0.005360,0.004464,0.003049,0.003011,0.002976,0.002865,0.002527,-0.000094,-0.001247,0.000913,0.008961,0.004197,0.002174,0.005660,0.003332,0.002570,0.003285,0.002734,0.002922,0.006108,0.002191,0.009677,0.004038,0.002923,0.004775,-0.000213,0.002254,-0.003074,0.002765,-0.002230

In [319]:
def crear_lags_wide(df, cols_base, lags):

    df = df.sort_values(["year", "semana"]).copy()

    for lag in range(1, lags + 1):
        lag_df = df[cols_base].shift(lag)
        lag_df.columns = [f"{col}_lag{lag}" for col in cols_base]
        df = pd.concat([df, lag_df], axis=1)

    return df

Dataset con 1 lag

In [320]:
cols_ret = [col for col in df_semanal.columns if col.startswith("ret_semanal_")]

weekly_semanal_1 = crear_lags_wide(
    df_semanal,
    cols_base=cols_ret,
    lags=1
)

pd.set_option("display.max_columns", None) 
weekly_semanal_1.head()

,week_key,year,semana,mes,inicio_mes,fin_mes,inicio_trimestre,fin_trimestre,ret_semanal_AGG,ret_semanal_BND,ret_semanal_DBC,ret_semanal_DIA,ret_semanal_DVY,ret_semanal_EEM,ret_semanal_EFA,ret_semanal_EWG,ret_semanal_EWJ,ret_semanal_EWQ,ret_semanal_EWT,ret_semanal_EWU,ret_semanal_EWZ,ret_semanal_FXI,ret_semanal_HYG,ret_semanal_IEF,ret_semanal_IEFA,ret_semanal_IEMG,ret_semanal_IJR,ret_semanal_INDA,ret_semanal_ITOT,ret_semanal_IVV,ret_semanal_IWD,ret_semanal_IWF,ret_semanal_IWM,ret_semanal_JNK,ret_semanal_LQD,ret_semanal_MCHI,ret_semanal_MDY,ret_semanal_MTUM,ret_semanal_QQQ,ret_semanal_QUAL,ret_semanal_SCHD,ret_semanal_SLV,ret_semanal_SPY,ret_semanal_TIP,ret_semanal_TLT,ret_semanal_USMV,ret_semanal_USO,ret_semanal_VEA,ret_semanal_VIG,ret_semanal_VLUE,ret_semanal_VNQ,ret_semanal_VOO,ret_semanal_VTI,ret_semanal_VTV,ret_semanal_VUG,ret_semanal_VWO,ret_semanal_XLB,ret_semanal_XLE,ret_semanal_XLF,ret_semanal_XLI,ret_semanal_XLK,ret_semanal_XLP,ret_semanal_XLRE,ret_semanal_XLU,ret_semanal_XLV,ret_semanal_XLY,volumen_log_diff_AGG,volumen_log_diff_BND,volumen_log_diff_DBC,volumen_log_diff_DIA,volumen_log_diff_DVY,volumen_log_diff_EEM,volumen_log_diff_EFA,volumen_log_diff_EWG,volumen_log_diff_EWJ,volumen_log_diff_EWQ,volumen_log_diff_EWT,volumen_log_diff_EWU,volumen_log_diff_EWZ,volumen_log_diff_FXI,volumen_log_diff_HYG,volumen_log_diff_IEF,volumen_log_diff_IEFA,volumen_log_diff_IEMG,volumen_log_diff_IJR,volumen_log_diff_INDA,volumen_log_diff_ITOT,volumen_log_diff_IVV,volumen_log_diff_IWD,volumen_log_diff_IWF,volumen_log_diff_IWM,volumen_log_diff_JNK,volumen_log_diff_LQD,volumen_log_diff_MCHI,volumen_log_diff_MDY,volumen_log_diff_MTUM,volumen_log_diff_QQQ,volumen_log_diff_QUAL,volumen_log_diff_SCHD,volumen_log_diff_SLV,volumen_log_diff_SPY,volumen_log_diff_TIP,volumen_log_diff_TLT,volumen_log_diff_USMV,volumen_log_diff_USO,volumen_log_diff_VEA,volumen_log_diff_VIG,volumen_log_diff_VLUE,volumen_log_diff_VNQ,volumen_log_diff_VOO,volumen_log_diff_VTI,volumen_log_diff_VTV,volumen_log_diff_VUG,volumen_log_diff_VWO,volumen_log_diff_XLB,volumen_log_diff_XLE,volumen_log_diff_XLF,volumen_log_diff_XLI,volumen_log_diff_XLK,volumen_log_diff_XLP,volumen_log_diff_XLRE,volumen_log_diff_XLU,volumen_log_diff_XLV,volumen_log_diff_XLY,target_AGG,target_BND,target_DBC,target_DIA,target_DVY,target_EEM,target_EFA,target_EWG,target_EWJ,target_EWQ,target_EWT,target_EWU,target_EWZ,target_FXI,target_HYG,target_IEF,target_IEFA,target_IEMG,target_IJR,target_INDA,target_ITOT,target_IVV,target_IWD,target_IWF,target_IWM,target_JNK,target_LQD,target_MCHI,target_MDY,target_MTUM,target_QQQ,target_QUAL,target_SCHD,target_SLV,target_SPY,target_TIP,target_TLT,target_USMV,target_USO,target_VEA,target_VIG,target_VLUE,target_VNQ,target_VOO,target_VTI,target_VTV,target_VUG,target_VWO,target_XLB,target_XLE,target_XLF,target_XLI,target_XLK,target_XLP,target_XLRE,target_XLU,target_XLV,target_XLY,ret_semanal_AGG_lag1,ret_semanal_BND_lag1,ret_semanal_DBC_lag1,ret_semanal_DIA_lag1,ret_semanal_DVY_lag1,ret_semanal_EEM_lag1,ret_semanal_EFA_lag1,ret_semanal_EWG_lag1,ret_semanal_EWJ_lag1,ret_semanal_EWQ_lag1,ret_semanal_EWT_lag1,ret_semanal_EWU_lag1,ret_semanal_EWZ_lag1,ret_semanal_FXI_lag1,ret_semanal_HYG_lag1,ret_semanal_IEF_lag1,ret_semanal_IEFA_lag1,ret_semanal_IEMG_lag1,ret_semanal_IJR_lag1,ret_semanal_INDA_lag1,ret_semanal_ITOT_lag1,ret_semanal_IVV_lag1,ret_semanal_IWD_lag1,ret_semanal_IWF_lag1,ret_semanal_IWM_lag1,ret_semanal_JNK_lag1,ret_semanal_LQD_lag1,ret_semanal_MCHI_lag1,ret_semanal_MDY_lag1,ret_semanal_MTUM_lag1,ret_semanal_QQQ_lag1,ret_semanal_QUAL_lag1,ret_semanal_SCHD_lag1,ret_semanal_SLV_lag1,ret_semanal_SPY_lag1,ret_semanal_TIP_lag1,ret_semanal_TLT_lag1,ret_semanal_USMV_lag1,ret_semanal_USO_lag1,ret_semanal_VEA_lag1,ret_semanal_VIG_lag1,ret_semanal_VLUE_lag1,ret_semanal_VNQ_lag1,ret_semanal_VOO_lag1,ret_semanal_VTI_lag1,ret_semanal_VTV_lag1,ret_semanal_VUG_lag1,ret_semanal_VWO_lag1,ret_semanal_XLB_lag1,ret_semanal_XLE_lag1,ret_semanal_XLF_lag1,ret_semanal_XLI_lag1,ret_semanal_XLK_lag1,ret_semanal_XLP_lag1,ret_semanal_XLRE_lag1,ret_semanal_XLU_lag1,ret_semanal_XLV_lag1,ret_semanal_XLY_lag1
0,2021-W01,2021,1,1,1,0,1,0,-0.002042,-0.002281,0.010383,0.007109,0.012052,0.012701,0.008017,0.005839,0.009299,0.006168,0.011315,0.012966,0.007608,0.010676,0.000716,-0.003652,0.008001,0.011714,0.017702,0.008355,0.009113,0.008249,0.010667,0.006692,0.017728,0.000804,-0.003056,0.012631,0.015672,0.012029,0.007735,0.006175,0.009732,-0.018838,0.008313,-0.001964,-0.010071,0.005358,0.022504,0.008591,0.006345,0.011569,0.002723,0.008261,0.009436,0.009851,0.007234,0.010313,0.016233,0.021808,0.015338,0.009091,0.005529,0.000674,0.001971,0.004901,0.009639,0.014278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-W02,2021,2,1,0,0,0,0,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575,-0.117361,-0.086574,-0.539732,-0.459750,-0.292106,-0.256894,-0.017097,-0.504441,-0.288985,0.146919,-0.384660,-0.024032,-0.021922,-0.680665,0.200763,-0.129573,0.133340,0.202425,0.300938,0.028507,-0.114187,0.205928,0.176201,0.052224,-0.149952,-0.075401,0.009488,-0.179850,-0.440872,0.933530,-0.243510,0.630144,-0.176504,-0.481412,-0.251597,-0.198469,-0.256328,0.642472,-0.516593,-0.123466,-0.090498,0.430339,0.262899,-0.227624,-0.393088,0.233110,0.333712,-0.265088,-0.673632,-0.004085,-0.095183,-0.250324,-0.153681,-0.279392,-0.182059,-0.069886,-0.536523,-0.028911,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401,-0.002042,-0.002281,0.010383,0.007109,0.012052,0.012701,0.008017,0.005839,0.009299,0.006168,0.011315,0.012966,0.007608,0.010676,0.000716,-0.003652,0.008001,0.011714,0.017702,0.008355,0.009113,0.008249,0.010667,0.006692,0.017728,0.000804,-0.003056,0.012631,0.015672,0.012029,0.007735,0.006175,0.009732,-0.018838,0.008313,-0.001964,-0.010071,0.005358,0.022504,0.008591,0.006345,0.011569,0.002723,0.008261,0.009436,0.009851,0.007234,0.010313,0.016233,0.021808,0.015338,0.009091,0.005529,0.000674,0.001971,0.004901,0.009639,0.014278
2,2021-W03,2021,3,1,0,0,0,0,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401,-0.108402,0.070663,0.225736,-0.215147,-0.009009,-0.037758,-0.170444,-0.251776,-0.130704,-1.392636,-0.052462,-0.323851,-0.110371,0.360270,-0.459197,-0.460806,-0.246064,-0.276663,-0.336541,-0.036602,-0.288774,-0.221239,-0.474917,0.014214,-0.230680,-0.249003,0.076559,0.133429,-0.073125,-0.825676,-0.118380,0.441607,0.017676,-0.405491,-0.135656,-0.103573,-0.378927,-0.545948,-0.283308,-0.213511,-0.118714,-0.916898,-0.275064,-0.138688,0.015674,-0.520023,-0.511758,-0.227270,-0.227945,-0.307283,0.009988,-0.185710,-0.344825,-0.190748,-0.199547,-0.007754,-0.225129,-0.215411,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575
3,2021-W04,2021,4,1,0,1,0,0,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746,-0.078063,-0.279824,-0.074341,0.775598,0.455206,0.059252,0.385649,0.546404,0.362695,0.400013,0.025057,0.270618,0.039978,0.044538,0.507807,0.296918,0.266312,-0.052148,0.312374,0.301928,0.550374,0.004164,0.438061,-0.088176,0.437582,0.808351,-0.091883,0.082252,0.123152,-0.083392,0.536044,0.441543,0.312325,1.083251,0.537474,-0.025717,0.202761,0.101343,0.133127,0.424749,0.190661,-0.141083,0.237280,0.409132,0.435398,0.036222,-0.005418,0.259145,0.523120,0.275833,0.171819,0.683245,0.463449,0.633732,0.787498,0.216596,0.497789,0.478444,-0.000698,-0.000760,0.008759,0.007676,0.009628,0.010701,0.006309,0.007364,0.006636,0.008167,0.009320,0.003931,0.011591,0.009225,0.001993,-0.001239,0.006879,0.010855,0.010696,0.015102,0.010069,0.009257,0.009361,0.009955,0.015072,0.002327,-0.000804,0.010852,0.011566,0.012135,0.010406,0.008818,0.007625,-0.000320,0.009313,-0.000438,-0.005062,0.005054,0.016419,0.007126,0.006828,0.008568,0.007281,0.009338,0.010170,0.007908,0.011039,0.010626,0.008019,0.015836,0.012972,0.009716,0.009675,0.005145,0.006319,0.004581,0.001110,0.012235,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401
4,2021-W05,2021,5,2,1,0,0,0,-0.000698,-0.000760,0.008759,0.007676,0.009628,0.010701,0.006309,0.007364,0.006636,0.008167,0.009320,0.003931,0.011591,0.009225,0.001993,-0.001239,0.006879,0.010855,0.010696,0.015102,0.010069,0.009257,0.009361,0.009955,0.015072,0.002327,-0.000804,0.010852,0.011566,0.012135,0.010406,0.008818,0.007625,-0.000320,0.009313,-0.000438,-0.005062,0.005054,0.016419,0.007126,0.006828,0.008568,0.007281,0.009338,0.010170,0.007908,0.011039,0.010626,0.008019,0.015836,0.012972,0.009716,0.009675,0.005145,0.006319,0.004581,0.001110,0.012235,-0.051107,-0.032336,0.656292,-0.655463,-0.928930,-0.211436,-0.576054,-0.382393,-0.182862,-0.762121,-0.096317,-0.487200,-0.192697,-0.257301,-0.353126,-0.438679,-0.352534,-0.204874,-0.494990,-0.287499,-0.118312,-0.346173,-0.160283,0.001141,-0.371301,-0.522335,-0.240154,-0.300759,-0.472664,0.170104,-0.446259,-1.255911,-0.268505,0.476288,-0.460796,0.328236,-0.092998,-0.334069,0.306580,-0.472144,-0.140701,-0.021730,-0.382191,-0.385021,-0.621943,-0.201325,-0.211008,-0.342546,-0.301719,-0.187869,-0.358571,-0.678380,-0.569198,-0.473119,-0.829476,-0.448354,-0.036454,-0.653051,-0.000223,-0.000276,0.005592,0.002234,0.003458,0.005472,0.004238,0.001891,0.006535,0.002591,0.004704,0.004906,-0.001107,0.007182,0.000593,-0.000068,0.004100,0.005503,0.007063,0.003755,0.003203,0.002584,0.003824,0.002561,0.004999,0.000694,-0.000163,0.008434,0.005360,0.004464,0.003049,0.003011,0.002976,0.002865,0.002527,-0.000094,-0.001247,0.000913,0.008961,0.004197,0.002174,0.005660,0.003332,0.002570,0.003285,0.002734,0.002922,0.006108,0.002191,0.009677,0.004038,0.002923,0.004775,-0.000213,0.002254,-0.003074,0.002765,-0.002230,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746

Dataset con 2 lags

In [321]:
weekly_semanal_2 =crear_lags_wide(
    df_semanal,
    cols_base=cols_ret,
    lags=2
)


pd.set_option("display.max_columns", None) 
weekly_semanal_2.head()

,week_key,year,semana,mes,inicio_mes,fin_mes,inicio_trimestre,fin_trimestre,ret_semanal_AGG,ret_semanal_BND,ret_semanal_DBC,ret_semanal_DIA,ret_semanal_DVY,ret_semanal_EEM,ret_semanal_EFA,ret_semanal_EWG,ret_semanal_EWJ,ret_semanal_EWQ,ret_semanal_EWT,ret_semanal_EWU,ret_semanal_EWZ,ret_semanal_FXI,ret_semanal_HYG,ret_semanal_IEF,ret_semanal_IEFA,ret_semanal_IEMG,ret_semanal_IJR,ret_semanal_INDA,ret_semanal_ITOT,ret_semanal_IVV,ret_semanal_IWD,ret_semanal_IWF,ret_semanal_IWM,ret_semanal_JNK,ret_semanal_LQD,ret_semanal_MCHI,ret_semanal_MDY,ret_semanal_MTUM,ret_semanal_QQQ,ret_semanal_QUAL,ret_semanal_SCHD,ret_semanal_SLV,ret_semanal_SPY,ret_semanal_TIP,ret_semanal_TLT,ret_semanal_USMV,ret_semanal_USO,ret_semanal_VEA,ret_semanal_VIG,ret_semanal_VLUE,ret_semanal_VNQ,ret_semanal_VOO,ret_semanal_VTI,ret_semanal_VTV,ret_semanal_VUG,ret_semanal_VWO,ret_semanal_XLB,ret_semanal_XLE,ret_semanal_XLF,ret_semanal_XLI,ret_semanal_XLK,ret_semanal_XLP,ret_semanal_XLRE,ret_semanal_XLU,ret_semanal_XLV,ret_semanal_XLY,volumen_log_diff_AGG,volumen_log_diff_BND,volumen_log_diff_DBC,volumen_log_diff_DIA,volumen_log_diff_DVY,volumen_log_diff_EEM,volumen_log_diff_EFA,volumen_log_diff_EWG,volumen_log_diff_EWJ,volumen_log_diff_EWQ,volumen_log_diff_EWT,volumen_log_diff_EWU,volumen_log_diff_EWZ,volumen_log_diff_FXI,volumen_log_diff_HYG,volumen_log_diff_IEF,volumen_log_diff_IEFA,volumen_log_diff_IEMG,volumen_log_diff_IJR,volumen_log_diff_INDA,volumen_log_diff_ITOT,volumen_log_diff_IVV,volumen_log_diff_IWD,volumen_log_diff_IWF,volumen_log_diff_IWM,volumen_log_diff_JNK,volumen_log_diff_LQD,volumen_log_diff_MCHI,volumen_log_diff_MDY,volumen_log_diff_MTUM,volumen_log_diff_QQQ,volumen_log_diff_QUAL,volumen_log_diff_SCHD,volumen_log_diff_SLV,volumen_log_diff_SPY,volumen_log_diff_TIP,volumen_log_diff_TLT,volumen_log_diff_USMV,volumen_log_diff_USO,volumen_log_diff_VEA,volumen_log_diff_VIG,volumen_log_diff_VLUE,volumen_log_diff_VNQ,volumen_log_diff_VOO,volumen_log_diff_VTI,volumen_log_diff_VTV,volumen_log_diff_VUG,volumen_log_diff_VWO,volumen_log_diff_XLB,volumen_log_diff_XLE,volumen_log_diff_XLF,volumen_log_diff_XLI,volumen_log_diff_XLK,volumen_log_diff_XLP,volumen_log_diff_XLRE,volumen_log_diff_XLU,volumen_log_diff_XLV,volumen_log_diff_XLY,target_AGG,target_BND,target_DBC,target_DIA,target_DVY,target_EEM,target_EFA,target_EWG,target_EWJ,target_EWQ,target_EWT,target_EWU,target_EWZ,target_FXI,target_HYG,target_IEF,target_IEFA,target_IEMG,target_IJR,target_INDA,target_ITOT,target_IVV,target_IWD,target_IWF,target_IWM,target_JNK,target_LQD,target_MCHI,target_MDY,target_MTUM,target_QQQ,target_QUAL,target_SCHD,target_SLV,target_SPY,target_TIP,target_TLT,target_USMV,target_USO,target_VEA,target_VIG,target_VLUE,target_VNQ,target_VOO,target_VTI,target_VTV,target_VUG,target_VWO,target_XLB,target_XLE,target_XLF,target_XLI,target_XLK,target_XLP,target_XLRE,target_XLU,target_XLV,target_XLY,ret_semanal_AGG_lag1,ret_semanal_BND_lag1,ret_semanal_DBC_lag1,ret_semanal_DIA_lag1,ret_semanal_DVY_lag1,ret_semanal_EEM_lag1,ret_semanal_EFA_lag1,ret_semanal_EWG_lag1,ret_semanal_EWJ_lag1,ret_semanal_EWQ_lag1,ret_semanal_EWT_lag1,ret_semanal_EWU_lag1,ret_semanal_EWZ_lag1,ret_semanal_FXI_lag1,ret_semanal_HYG_lag1,ret_semanal_IEF_lag1,ret_semanal_IEFA_lag1,ret_semanal_IEMG_lag1,ret_semanal_IJR_lag1,ret_semanal_INDA_lag1,ret_semanal_ITOT_lag1,ret_semanal_IVV_lag1,ret_semanal_IWD_lag1,ret_semanal_IWF_lag1,ret_semanal_IWM_lag1,ret_semanal_JNK_lag1,ret_semanal_LQD_lag1,ret_semanal_MCHI_lag1,ret_semanal_MDY_lag1,ret_semanal_MTUM_lag1,ret_semanal_QQQ_lag1,ret_semanal_QUAL_lag1,ret_semanal_SCHD_lag1,ret_semanal_SLV_lag1,ret_semanal_SPY_lag1,ret_semanal_TIP_lag1,ret_semanal_TLT_lag1,ret_semanal_USMV_lag1,ret_semanal_USO_lag1,ret_semanal_VEA_lag1,ret_semanal_VIG_lag1,ret_semanal_VLUE_lag1,ret_semanal_VNQ_lag1,ret_semanal_VOO_lag1,ret_semanal_VTI_lag1,ret_semanal_VTV_lag1,ret_semanal_VUG_lag1,ret_semanal_VWO_lag1,ret_semanal_XLB_lag1,ret_semanal_XLE_lag1,ret_semanal_XLF_lag1,ret_semanal_XLI_lag1,ret_semanal_XLK_lag1,ret_semanal_XLP_lag1,ret_semanal_XLRE_lag1,ret_semanal_XLU_lag1,ret_semanal_XLV_lag1,ret_semanal_XLY_lag1,ret_semanal_AGG_lag2,ret_semanal_BND_lag2,ret_semanal_DBC_lag2,ret_semanal_DIA_lag2,ret_semanal_DVY_lag2,ret_semanal_EEM_lag2,ret_semanal_EFA_lag2,ret_semanal_EWG_lag2,ret_semanal_EWJ_lag2,ret_semanal_EWQ_lag2,ret_semanal_EWT_lag2,ret_semanal_EWU_lag2,ret_semanal_EWZ_lag2,ret_semanal_FXI_lag2,ret_semanal_HYG_lag2,ret_semanal_IEF_lag2,ret_semanal_IEFA_lag2,ret_semanal_IEMG_lag2,ret_semanal_IJR_lag2,ret_semanal_INDA_lag2,ret_semanal_ITOT_lag2,ret_semanal_IVV_lag2,ret_semanal_IWD_lag2,ret_semanal_IWF_lag2,ret_semanal_IWM_lag2,ret_semanal_JNK_lag2,ret_semanal_LQD_lag2,ret_semanal_MCHI_lag2,ret_semanal_MDY_lag2,ret_semanal_MTUM_lag2,ret_semanal_QQQ_lag2,ret_semanal_QUAL_lag2,ret_semanal_SCHD_lag2,ret_semanal_SLV_lag2,ret_semanal_SPY_lag2,ret_semanal_TIP_lag2,ret_semanal_TLT_lag2,ret_semanal_USMV_lag2,ret_semanal_USO_lag2,ret_semanal_VEA_lag2,ret_semanal_VIG_lag2,ret_semanal_VLUE_lag2,ret_semanal_VNQ_lag2,ret_semanal_VOO_lag2,ret_semanal_VTI_lag2,ret_semanal_VTV_lag2,ret_semanal_VUG_lag2,ret_semanal_VWO_lag2,ret_semanal_XLB_lag2,ret_semanal_XLE_lag2,ret_semanal_XLF_lag2,ret_semanal_XLI_lag2,ret_semanal_XLK_lag2,ret_semanal_XLP_lag2,ret_semanal_XLRE_lag2,ret_semanal_XLU_lag2,ret_semanal_XLV_lag2,ret_semanal_XLY_lag2
0,2021-W01,2021,1,1,1,0,1,0,-0.002042,-0.002281,0.010383,0.007109,0.012052,0.012701,0.008017,0.005839,0.009299,0.006168,0.011315,0.012966,0.007608,0.010676,0.000716,-0.003652,0.008001,0.011714,0.017702,0.008355,0.009113,0.008249,0.010667,0.006692,0.017728,0.000804,-0.003056,0.012631,0.015672,0.012029,0.007735,0.006175,0.009732,-0.018838,0.008313,-0.001964,-0.010071,0.005358,0.022504,0.008591,0.006345,0.011569,0.002723,0.008261,0.009436,0.009851,0.007234,0.010313,0.016233,0.021808,0.015338,0.009091,0.005529,0.000674,0.001971,0.004901,0.009639,0.014278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-W02,2021,2,1,0,0,0,0,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575,-0.117361,-0.086574,-0.539732,-0.459750,-0.292106,-0.256894,-0.017097,-0.504441,-0.288985,0.146919,-0.384660,-0.024032,-0.021922,-0.680665,0.200763,-0.129573,0.133340,0.202425,0.300938,0.028507,-0.114187,0.205928,0.176201,0.052224,-0.149952,-0.075401,0.009488,-0.179850,-0.440872,0.933530,-0.243510,0.630144,-0.176504,-0.481412,-0.251597,-0.198469,-0.256328,0.642472,-0.516593,-0.123466,-0.090498,0.430339,0.262899,-0.227624,-0.393088,0.233110,0.333712,-0.265088,-0.673632,-0.004085,-0.095183,-0.250324,-0.153681,-0.279392,-0.182059,-0.069886,-0.536523,-0.028911,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401,-0.002042,-0.002281,0.010383,0.007109,0.012052,0.012701,0.008017,0.005839,0.009299,0.006168,0.011315,0.012966,0.007608,0.010676,0.000716,-0.003652,0.008001,0.011714,0.017702,0.008355,0.009113,0.008249,0.010667,0.006692,0.017728,0.000804,-0.003056,0.012631,0.015672,0.012029,0.007735,0.006175,0.009732,-0.018838,0.008313,-0.001964,-0.010071,0.005358,0.022504,0.008591,0.006345,0.011569,0.002723,0.008261,0.009436,0.009851,0.007234,0.010313,0.016233,0.021808,0.015338,0.009091,0.005529,0.000674,0.001971,0.004901,0.009639,0.014278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-W03,2021,3,1,0,0,0,0,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401,-0.108402,0.070663,0.225736,-0.215147,-0.009009,-0.037758,-0.170444,-0.251776,-0.130704,-1.392636,-0.052462,-0.323851,-0.110371,0.360270,-0.459197,-0.460806,-0.246064,-0.276663,-0.336541,-0.036602,-0.288774,-0.221239,-0.474917,0.014214,-0.230680,-0.249003,0.076559,0.133429,-0.073125,-0.825676,-0.118380,0.441607,0.017676,-0.405491,-0.135656,-0.103573,-0.378927,-0.545948,-0.283308,-0.213511,-0.118714,-0.916898,-0.275064,-0.138688,0.015674,-0.520023,-0.511758,-0.227270,-0.227945,-0.307283,0.009988,-0.185710,-0.344825,-0.190748,-0.199547,-0.007754,-0.225129,-0.215411,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575,-0.002042,-0.002281,0.010383,0.007109,0.012052,0.012701,0.008017,0.005839,0.009299,0.006168,0.011315,0.012966,0.007608,0.010676,0.000716,-0.003652,0.008001,0.011714,0.017702,0.008355,0.009113,0.008249,0.010667,0.006692,0.017728,0.000804,-0.003056,0.012631,0.015672,0.012029,0.007735,0.006175,0.009732,-0.018838,0.008313,-0.001964,-0.010071,0.005358,0.022504,0.008591,0.006345,0.011569,0.002723,0.008261,0.009436,0.009851,0.007234,0.010313,0.016233,0.021808,0.015338,0.009091,0.005529,0.000674,0.001971,0.004901,0.009639,0.014278
3,2021-W04,2021,4,1,0,1,0,0,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746,-0.078063,-0.279824,-0.074341,0.775598,0.455206,0.059252,0.385649,0.546404,0.362695,0.400013,0.025057,0.270618,0.039978,0.044538,0.507807,0.296918,0.266312,-0.052148,0.312374,0.301928,0.550374,0.004164,0.438061,-0.088176,0.437582,0.808351,-0.091883,0.082252,0.123152,-0.083392,0.536044,0.441543,0.312325,1.083251,0.537474,-0.025717,0.202761,0.101343,0.133127,0.424749,0.190661,-0.141083,0.237280,0.409132,0.435398,0.036222,-0.005418,0.259145,0.523120,0.275833,0.171819,0.683245,0.463449,0.633732,0.787498,0.216596,0.497789,0.478444,-0.000698,-0.000760,0.008759,0.007676,0.009628,0.010701,0.006309,0.007364,0.006636,0.008167,0.009320,0.003931,0.011591,0.009225,0.001993,-0.001239,0.006879,0.010855,0.010696,0.015102,0.010069,0.009257,0.009361,0.009955,0.015072,0.002327,-0.000804,0.010852,0.011566,0.012135,0.010406,0.008818,0.007625,-0.000320,0.009313,-0.000438,-0.005062,0.005054,0.016419,0.007126,0.006828,0.008568,0.007281,0.009338,0.010170,0.007908,0.011039,0.010626,0.008019,0.015836,0.012972,0.009716,0.009675,0.005145,0.006319,0.004581,0.001110,0.012235,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575
4,2021-W05,2021,5,2,1,0,0,0,-0.000698,-0.000760,0.008759,0.007676,0.009628,0.010701,0.006309,0.007364,0.006636,0.008167,0.009320,0.003931,0.011591,0.009225,0.001993,-0.001239,0.006879,0.010855,0.010696,0.015102,0.010069,0.009257,0.009361,0.009955,0.015072,0.002327,-0.000804,0.010852,0.011566,0.012135,0.010406,0.008818,0.007625,-0.000320,0.009313,-0.000438,-0.005062,0.005054,0.016419,0.007126,0.006828,0.008568,0.007281,0.009338,0.010170,0.007908,0.011039,0.010626,0.008019,0.015836,0.012972,0.009716,0.009675,0.005145,0.006319,0.004581,0.001110,0.012235,-0.051107,-0.032336,0.656292,-0.655463,-0.928930,-0.211436,-0.576054,-0.382393,-0.182862,-0.762121,-0.096317,-0.487200,-0.192697,-0.257301,-0.353126,-0.438679,-0.352534,-0.204874,-0.494990,-0.287499,-0.118312,-0.346173,-0.160283,0.001141,-0.371301,-0.522335,-0.240154,-0.300759,-0.472664,0.170104,-0.446259,-1.255911,-0.268505,0.476288,-0.460796,0.328236,-0.092998,-0.334069,0.306580,-0.472144,-0.140701,-0.021730,-0.382191,-0.385021,-0.621943,-0.201325,-0.211008,-0.342546,-0.301719,-0.187869,-0.358571,-0.678380,-0.569198,-0.473119,-0.829476,-0.448354,-0.036454,-0.653051,-0.000223,-0.000276,0.005592,0.002234,0.003458,0.005472,0.004238,0.001891,0.006535,0.002591,0.004704,0.004906,-0.001107,0.007182,0.000593,-0.000068,0.004100,0.005503,0.007063,0.003755,0.003203,0.002584,0.003824,0.002561,0.004999,0.000694,-0.000163,0.008434,0.005360,0.004464,0.003049,0.003011,0.002976,0.002865,0.002527,-0.000094,-0.001247,0.000913,0.008961,0.004197,0.002174,0.005660,0.003332,0.002570,0.003285,0.002734,0.002922,0.006108,0.002191,0.009677,0.004038,0.002923,0.004775,-0.000213,0.002254,-0.003074,0.002765,-0.002230,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401

In [322]:
weekly_semanal_3 = crear_lags_wide(
    df_semanal,
    cols_base=cols_ret,
    lags=3
)

In [323]:
weekly_semanal_4 = crear_lags_wide(
    df_semanal,
    cols_base=cols_ret,
    lags=4
)

In [324]:
import os

def guardar_dataset(df, nombre_archivo):
    
    out_dir = "../Datos_csv"
    os.makedirs(out_dir, exist_ok=True)

    path = os.path.join(out_dir, nombre_archivo)

    df.to_csv(path, index=False)

    print("Guardado:")
    print(" -", path, df.shape)

In [325]:
df_semanal = df_semanal.dropna().reset_index(drop=True)
weekly_semanal_1 = weekly_semanal_1.dropna().reset_index(drop=True)
weekly_semanal_2 = weekly_semanal_2.dropna().reset_index(drop=True)
weekly_semanal_3 = weekly_semanal_3.dropna().reset_index(drop=True)
weekly_semanal_4 = weekly_semanal_4.dropna().reset_index(drop=True)

In [326]:
# # columnas a eliminar como features
# cols_borrar = ["week_key", "year", "semana", "mes"]

# # eliminar solo si existen
# df_semanal = df_semanal.drop(columns=cols_borrar, errors="ignore")
# weekly_semanal_1 = weekly_semanal_1.drop(columns=cols_borrar, errors="ignore")
# weekly_semanal_2 = weekly_semanal_2.drop(columns=cols_borrar, errors="ignore")
# weekly_semanal_3 = weekly_semanal_3.drop(columns=cols_borrar, errors="ignore")
# weekly_semanal_4 = weekly_semanal_4.drop(columns=cols_borrar, errors="ignore")

In [327]:
pd.set_option("display.max_columns", None) 
df_semanal.head()

,week_key,year,semana,mes,inicio_mes,fin_mes,inicio_trimestre,fin_trimestre,ret_semanal_AGG,ret_semanal_BND,ret_semanal_DBC,ret_semanal_DIA,ret_semanal_DVY,ret_semanal_EEM,ret_semanal_EFA,ret_semanal_EWG,ret_semanal_EWJ,ret_semanal_EWQ,ret_semanal_EWT,ret_semanal_EWU,ret_semanal_EWZ,ret_semanal_FXI,ret_semanal_HYG,ret_semanal_IEF,ret_semanal_IEFA,ret_semanal_IEMG,ret_semanal_IJR,ret_semanal_INDA,ret_semanal_ITOT,ret_semanal_IVV,ret_semanal_IWD,ret_semanal_IWF,ret_semanal_IWM,ret_semanal_JNK,ret_semanal_LQD,ret_semanal_MCHI,ret_semanal_MDY,ret_semanal_MTUM,ret_semanal_QQQ,ret_semanal_QUAL,ret_semanal_SCHD,ret_semanal_SLV,ret_semanal_SPY,ret_semanal_TIP,ret_semanal_TLT,ret_semanal_USMV,ret_semanal_USO,ret_semanal_VEA,ret_semanal_VIG,ret_semanal_VLUE,ret_semanal_VNQ,ret_semanal_VOO,ret_semanal_VTI,ret_semanal_VTV,ret_semanal_VUG,ret_semanal_VWO,ret_semanal_XLB,ret_semanal_XLE,ret_semanal_XLF,ret_semanal_XLI,ret_semanal_XLK,ret_semanal_XLP,ret_semanal_XLRE,ret_semanal_XLU,ret_semanal_XLV,ret_semanal_XLY,volumen_log_diff_AGG,volumen_log_diff_BND,volumen_log_diff_DBC,volumen_log_diff_DIA,volumen_log_diff_DVY,volumen_log_diff_EEM,volumen_log_diff_EFA,volumen_log_diff_EWG,volumen_log_diff_EWJ,volumen_log_diff_EWQ,volumen_log_diff_EWT,volumen_log_diff_EWU,volumen_log_diff_EWZ,volumen_log_diff_FXI,volumen_log_diff_HYG,volumen_log_diff_IEF,volumen_log_diff_IEFA,volumen_log_diff_IEMG,volumen_log_diff_IJR,volumen_log_diff_INDA,volumen_log_diff_ITOT,volumen_log_diff_IVV,volumen_log_diff_IWD,volumen_log_diff_IWF,volumen_log_diff_IWM,volumen_log_diff_JNK,volumen_log_diff_LQD,volumen_log_diff_MCHI,volumen_log_diff_MDY,volumen_log_diff_MTUM,volumen_log_diff_QQQ,volumen_log_diff_QUAL,volumen_log_diff_SCHD,volumen_log_diff_SLV,volumen_log_diff_SPY,volumen_log_diff_TIP,volumen_log_diff_TLT,volumen_log_diff_USMV,volumen_log_diff_USO,volumen_log_diff_VEA,volumen_log_diff_VIG,volumen_log_diff_VLUE,volumen_log_diff_VNQ,volumen_log_diff_VOO,volumen_log_diff_VTI,volumen_log_diff_VTV,volumen_log_diff_VUG,volumen_log_diff_VWO,volumen_log_diff_XLB,volumen_log_diff_XLE,volumen_log_diff_XLF,volumen_log_diff_XLI,volumen_log_diff_XLK,volumen_log_diff_XLP,volumen_log_diff_XLRE,volumen_log_diff_XLU,volumen_log_diff_XLV,volumen_log_diff_XLY,target_AGG,target_BND,target_DBC,target_DIA,target_DVY,target_EEM,target_EFA,target_EWG,target_EWJ,target_EWQ,target_EWT,target_EWU,target_EWZ,target_FXI,target_HYG,target_IEF,target_IEFA,target_IEMG,target_IJR,target_INDA,target_ITOT,target_IVV,target_IWD,target_IWF,target_IWM,target_JNK,target_LQD,target_MCHI,target_MDY,target_MTUM,target_QQQ,target_QUAL,target_SCHD,target_SLV,target_SPY,target_TIP,target_TLT,target_USMV,target_USO,target_VEA,target_VIG,target_VLUE,target_VNQ,target_VOO,target_VTI,target_VTV,target_VUG,target_VWO,target_XLB,target_XLE,target_XLF,target_XLI,target_XLK,target_XLP,target_XLRE,target_XLU,target_XLV,target_XLY
0,2021-W02,2021,2,1,0,0,0,0,0.000290,0.000183,0.000786,-0.001804,0.002915,-0.001320,-0.003544,-0.006671,-0.001652,-0.005888,0.003209,-0.004595,-0.004344,0.001238,-0.000596,0.000355,-0.003856,-0.001255,0.003731,-0.003339,-0.002004,-0.002917,-0.000227,-0.004766,0.002896,-0.000606,0.000559,0.000468,0.000526,-0.003981,-0.004546,-0.003442,0.000395,-0.004822,-0.002938,0.000599,0.000660,-0.003214,-0.000509,-0.003780,-0.002962,0.005531,0.003674,-0.002903,-0.002210,0.000278,-0.005427,0.000152,-0.003082,0.006321,0.000129,-0.001748,-0.005175,-0.003833,0.003778,0.002107,-0.000717,-0.003575,-0.117361,-0.086574,-0.539732,-0.459750,-0.292106,-0.256894,-0.017097,-0.504441,-0.288985,0.146919,-0.384660,-0.024032,-0.021922,-0.680665,0.200763,-0.129573,0.133340,0.202425,0.300938,0.028507,-0.114187,0.205928,0.176201,0.052224,-0.149952,-0.075401,0.009488,-0.179850,-0.440872,0.933530,-0.243510,0.630144,-0.176504,-0.481412,-0.251597,-0.198469,-0.256328,0.642472,-0.516593,-0.123466,-0.090498,0.430339,0.262899,-0.227624,-0.393088,0.233110,0.333712,-0.265088,-0.673632,-0.004085,-0.095183,-0.250324,-0.153681,-0.279392,-0.182059,-0.069886,-0.536523,-0.028911,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401
1,2021-W03,2021,3,1,0,0,0,0,0.000000,0.000086,-0.003455,0.001497,-0.002190,0.006717,0.002508,0.005514,0.001885,0.000075,0.005620,0.000572,-0.012863,0.015404,0.000545,0.000274,0.002861,0.006517,0.003986,0.002186,0.004676,0.004735,-0.000605,0.009404,0.004991,0.000574,-0.000809,0.015312,0.004069,0.008919,0.010641,0.003191,-0.000570,0.007617,0.004733,0.001177,0.000099,0.001666,-0.000779,0.002476,0.000390,0.000700,0.003404,0.004683,0.004812,-0.001044,0.009541,0.007043,-0.003206,-0.004009,-0.004896,-0.000902,0.010395,-0.002142,0.003281,-0.000596,0.001322,0.006401,-0.108402,0.070663,0.225736,-0.215147,-0.009009,-0.037758,-0.170444,-0.251776,-0.130704,-1.392636,-0.052462,-0.323851,-0.110371,0.360270,-0.459197,-0.460806,-0.246064,-0.276663,-0.336541,-0.036602,-0.288774,-0.221239,-0.474917,0.014214,-0.230680,-0.249003,0.076559,0.133429,-0.073125,-0.825676,-0.118380,0.441607,0.017676,-0.405491,-0.135656,-0.103573,-0.378927,-0.545948,-0.283308,-0.213511,-0.118714,-0.916898,-0.275064,-0.138688,0.015674,-0.520023,-0.511758,-0.227270,-0.227945,-0.307283,0.009988,-0.185710,-0.344825,-0.190748,-0.199547,-0.007754,-0.225129,-0.215411,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746
2,2021-W04,2021,4,1,0,1,0,0,0.000102,0.000114,0.001321,-0.006665,-0.006710,-0.009238,-0.007484,-0.006812,-0.006607,-0.006620,-0.011038,-0.009360,-0.004911,-0.009302,-0.000757,0.000101,-0.007470,-0.009246,-0.007227,-0.010985,-0.006993,-0.006769,-0.007008,-0.006853,-0.008980,-0.000994,-0.000147,-0.007930,-0.010304,-0.008097,-0.006788,-0.006585,-0.006684,0.010938,-0.006806,0.000344,0.000158,-0.005114,-0.000284,-0.007660,-0.005640,-0.007069,-0.001898,-0.006774,-0.006990,-0.006338,-0.007106,-0.008783,-0.010318,-0.013520,-0.009379,-0.008635,-0.005960,-0.003035,-0.000326,-0.002208,-0.004402,-0.009746,-0.078063,-0.279824,-0.074341,0.775598,0.455206,0.059252,0.385649,0.546404,0.362695,0.400013,0.025057,0.270618,0.039978,0.044538,0.507807,0.296918,0.266312,-0.052148,0.312374,0.301928,0.550374,0.004164,0.438061,-0.088176,0.437582,0.808351,-0.091883,0.082252,0.123152,-0.083392,0.536044,0.441543,0.312325,1.083251,0.537474,-0.025717,0.202761,0.101343,0.133127,0.424749,0.190661,-0.141083,0.237280,0.409132,0.435398,0.036222,-0.005418,0.259145,0.523120,0.275833,0.171819,0.683245,0.463449,0.633732,0.787498,0.216596,0.497789,0.478444,-0.000698,-0.000760,0.008759,0.007676,0.009628,0.010701,0.006309,0.007364,0.006636,0.008167,0.009320,0.003931,0.011591,0.009225,0.001993,-0.001239,0.006879,0.010855,0.010696,0.015102,0.010069,0.009257,0.009361,0.009955,0.015072,0.002327,-0.000804,0.010852,0.011566,0.012135,0.010406,0.008818,0.007625,-0.000320,0.009313,-0.000438,-0.005062,0.005054,0.016419,0.007126,0.006828,0.008568,0.007281,0.009338,0.010170,0.007908,0.011039,0.010626,0.008019,0.015836,0.012972,0.009716,0.009675,0.005145,0.006319,0.004581,0.001110,0.012235
3,2021-W05,2021,5,2,1,0,0,0,-0.000698,-0.000760,0.008759,0.007676,0.009628,0.010701,0.006309,0.007364,0.006636,0.008167,0.009320,0.003931,0.011591,0.009225,0.001993,-0.001239,0.006879,0.010855,0.010696,0.015102,0.010069,0.009257,0.009361,0.009955,0.015072,0.002327,-0.000804,0.010852,0.011566,0.012135,0.010406,0.008818,0.007625,-0.000320,0.009313,-0.000438,-0.005062,0.005054,0.016419,0.007126,0.006828,0.008568,0.007281,0.009338,0.010170,0.007908,0.011039,0.010626,0.008019,0.015836,0.012972,0.009716,0.009675,0.005145,0.006319,0.004581,0.001110,0.012235,-0.051107,-0.032336,0.656292,-0.655463,-0.928930,-0.211436,-0.576054,-0.382393,-0.182862,-0.762121,-0.096317,-0.487200,-0.192697,-0.257301,-0.353126,-0.438679,-0.352534,-0.204874,-0.494990,-0.287499,-0.118312,-0.346173,-0.160283,0.001141,-0.371301,-0.522335,-0.240154,-0.300759,-0.472664,0.170104,-0.446259,-1.255911,-0.268505,0.476288,-0.460796,0.328236,-0.092998,-0.334069,0.306580,-0.472144,-0.140701,-0.021730,-0.382191,-0.385021,-0.621943,-0.201325,-0.211008,-0.342546,-0.301719,-0.187869,-0.358571,-0.678380,-0.569198,-0.473119,-0.829476,-0.448354,-0.036454,-0.653051,-0.000223,-0.000276,0.005592,0.002234,0.003458,0.005472,0.004238,0.001891,0.006535,0.002591,0.004704,0.004906,-0.001107,0.007182,0.000593,-0.000068,0.004100,0.005503,0.007063,0.003755,0.003203,0.002584,0.003824,0.002561,0.004999,0.000694,-0.000163,0.008434,0.005360,0.004464,0.003049,0.003011,0.002976,0.002865,0.002527,-0.000094,-0.001247,0.000913,0.008961,0.004197,0.002174,0.005660,0.003332,0.002570,0.003285,0.002734,0.002922,0.006108,0.002191,0.009677,0.004038,0.002923,0.004775,-0.000213,0.002254,-0.003074,0.002765,-0.002230
4,2021-W06,2021,6,2,0,0,0,0,-0.000223,-0.000276,0.005592,0.002234,0.003458,0.005472,0.004238,0.001891,0.006535,0.002591,0.004704,0.004906,-0.001107,0.007182,0.000593,-0.000068,0.004100,0.005503,0.007063,0.003755,0.003203,0.002584,0.003824,0.002561,0.004999,0.000694,-0.000163,0.008434,0.005360,0.004464,0.003049,0.003011,0.002976,0.002865,0.002527,-0.000094,-0.001247,0.000913,0.008961,0.004197,0.002174,0.005660,0.003332,0.002570,0.003285,0.002734,0.002922,0.006108,0.002191,0.009677,0.004038,0.002923,0.004775,-0.000213,0.002254,-0.003074,0.002765,-0.002230,-0.324176,-0.020061,-0.485617,-0.164462,-0.155708,-0.146744,-0.054127,-0.370626,-0.266721,1.374895,-0.218236,-0.085736,-0.109667,-0.113115,-0.482885,0.429746,-0.272959,-0.478026,-0.042411,-0.088261,-0.234119,-0.010489,-0.533438,-0.706850,-0.087679,-0.395311,-0.029096,-0.014753,-0.038248,0.012412,-0.250999,0.208617,-0.188893,-1.207939,-0.241636,-0.511390,0.112675,0.000478,-0.186055,-0.028137,-0.351485,0.141954,-0.365041,-0.133352,-0.010583,-0.026515,0.026763,-0.134187,-0.191343,-0.045673,-0.242465,-0.022864,-0.061054,-0.187985,-0.264425,-0.048373,-0.511650,-0.191088,-0.001592,-0.001675,0.003045,0.000381,0.005436,-0.001171,-0.000197,-0.001981,-0.000735,0.001386,0.002889,0.003495,-0.002440,0.000140,-0.000799,-0.002667,-0.000173,-0.000795,-0.001505,-0.001633,-0.001610,-0.001699,0.000570,-0.004247,-0.002288,-0.000777,-0.002819,-0.001901,-0.000913,-0.004863,-0.004068,-0.001654,0.002856,-0.000494,-0.001667,-0.003431,-0.006613,-0.003367,-0.001633,-0.000505,-0.002682,0.001912,-0.001877,-0.001709,-0.001838,0.000742,-0.003869,-0.000579,0.002376,0.008311,0.006961,0.001876,-0.004624,-0.002871,-0.001831,-0.004878,-0.006194,-0.001030

In [328]:
df_semanal.shape

(264, 182)

In [329]:
weekly_semanal_2.shape

(263, 298)

In [330]:
guardar_dataset(df_semanal, "df_semanal.csv")
guardar_dataset(weekly_semanal_1, "df_semanal_1.csv")
guardar_dataset(weekly_semanal_2, "df_semanal_2.csv")
guardar_dataset(weekly_semanal_3, "df_semanal_3.csv")
guardar_dataset(weekly_semanal_4, "df_semanal_4.csv")

Guardado:
 - ../Datos_csv\df_semanal.csv (264, 182)

Guardado:
 - ../Datos_csv\df_semanal_1.csv (264, 240)
Guardado:
 - ../Datos_csv\df_semanal_2.csv (263, 298)
Guardado:
 - ../Datos_csv\df_semanal_3.csv (262, 356)
Guardado:
 - ../Datos_csv\df_semanal_4.csv (261, 414)