In [4]:
import pandas as pd


df_diario = pd.read_csv( "../Datos_csv/df_diario.csv",parse_dates=True)
# df_diario_1 = pd.read_csv("../Datos_csv/df_diario_1.csv",index_col=0,parse_dates=True)
# df_diario_2 = pd.read_csv("../Datos_csv/df_diario_2.csv",index_col=0,parse_dates=True)
# df_diario_3 = pd.read_csv("../Datos_csv/df_diario_3.csv",index_col=0,parse_dates=True)
# df_diario_4 = pd.read_csv("../Datos_csv/df_diario_4.csv",index_col=0,parse_dates=True)
# df_diario_5 = pd.read_csv("../Datos_csv/df_diario_5.csv",index_col=0,parse_dates=True)
# df_diario_6 = pd.read_csv("../Datos_csv/df_diario_6.csv",index_col=0,parse_dates=True)
# df_diario_7 = pd.read_csv("../Datos_csv/df_diario_7.csv",index_col=0,parse_dates=True)
# df_diario_8 = pd.read_csv("../Datos_csv/df_diario_8.csv",index_col=0,parse_dates=True)

In [5]:
df_diario.head(5)

,Date,AGG,BND,DBC,DIA,DVY,EEM,EFA,EWG,EWJ,...,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY,year
0,2021-01-04,101.754219,75.627838,12.721416,276.643707,79.074379,46.271244,62.786320,28.436781,59.164673,...,15.711834,26.672197,80.046921,61.501385,58.505482,29.902739,26.242632,104.278328,76.565468,2021
1,2021-01-05,101.650749,75.499046,13.078175,278.034576,79.983955,47.383541,63.436947,28.578253,59.714134,...,16.415474,26.791439,80.834328,61.900486,58.505482,29.868925,26.238338,105.035362,77.137001,2021
2,2021-01-06,101.150787,75.164131,13.095576,282.033569,83.146599,46.983116,64.164619,28.834682,60.423111,...,16.916294,27.974627,82.761154,60.832996,58.549316,29.725246,26.890974,106.475594,77.924644,2021
3,2021-01-07,101.047356,75.009575,13.156486,284.129028,83.405289,47.428032,64.233139,28.976160,60.299049,...,17.164644,28.378201,83.215073,62.472691,58.373955,29.818226,26.538897,107.860458,79.427902,2021
4,2021-01-08,100.926666,74.940857,13.260902,284.623169,82.979713,48.682690,64.832397,29.108793,61.406837,...,17.143942,28.359854,83.011261,62.876617,58.663319,30.139393,26.762159,108.377434,81.065636,2021

Intenta responder dos preguntas:
- Qué modelo predice mejor
        LinearRegression

        Ridge

        RandomForest

        XGBoost

        LightGBM

        MLP

        LSTM
- Cuánta memoria temporal es útil

In [ ]:
adj_close.head()

,Date,AGG,BND,DBC,DIA,DVY,EEM,EFA,EWG,EWJ,...,XLE,XLF,XLI,XLK,XLP,XLRE,XLU,XLV,XLY,year
0,2021-01-04,101.754219,75.627838,12.721416,276.643707,79.074379,46.271244,62.786320,28.436781,59.164673,...,15.711834,26.672197,80.046921,61.501385,58.505482,29.902739,26.242632,104.278328,76.565468,2021
1,2021-01-05,101.650749,75.499046,13.078175,278.034576,79.983955,47.383541,63.436947,28.578253,59.714134,...,16.415474,26.791439,80.834328,61.900486,58.505482,29.868925,26.238338,105.035362,77.137001,2021
2,2021-01-06,101.150787,75.164131,13.095576,282.033569,83.146599,46.983116,64.164619,28.834682,60.423111,...,16.916294,27.974627,82.761154,60.832996,58.549316,29.725246,26.890974,106.475594,77.924644,2021
3,2021-01-07,101.047356,75.009575,13.156486,284.129028,83.405289,47.428032,64.233139,28.976160,60.299049,...,17.164644,28.378201,83.215073,62.472691,58.373955,29.818226,26.538897,107.860458,79.427902,2021
4,2021-01-08,100.926666,74.940857,13.260902,284.623169,82.979713,48.682690,64.832397,29.108793,61.406837,...,17.143942,28.359854,83.011261,62.876617,58.663319,30.139393,26.762159,108.377434,81.065636,2021

## Linear Regression (Ridge / Lasso / ElasticNet)

## Random Forest

## Gradient Boosting

### XGBoost

### LightGBM

## Redes neuronales

### MLP (Multilayer Perceptron)

### LSTM (Long Short-Term Memory)